invoer = ('5-9-7-1-7-8-3-2-4-8-7-9')
lst = invoer.split('-')
print(lst)
lst.sort()
print('Gesorteerde list van ints: ' + str(lst))
print("grootste getal: " + max(lst) + " en het kleinste getal: " + min(lst))
a = len(lst)
# print("Aantal getallen: "+len(lst) 'en Som van de getallen: ' , sum(lst))
# print("gemiddelde: " +sum(lst)/len(lst))
